apiVersion: v1
kind: Service
metadata:
  name: webapp-web-dashboard
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 80
      
  selector:
    name: web-dashboard
---
apiVersion: apps/v1
kind: Deployment
metadata: 
   name: deployment-web-dashboard
   labels: 
      name: web-dashboard
spec: 
   replicas: 1
   selector: 
      matchLabels: 
         name: web-dashboard
   template:
      metadata:
         labels:
            name: web-dashboard
      spec:
         containers:
         - name: web-dashboard
           image: gcr.io/kodekloud/customimage/my-kubernetes-dashboard
           ports:
           - containerPort: 8080 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: lab-dash-ingress
  namespace: default
spec:
  rules:
  - host: lab-dash.test

    http:
      paths: 
      - pathType: ImplementationSpecific
        backend: 
          service: 
            name: webapp-web-dashboard
            port:
              number: 80