apiVersion: v1
kind: Namespace
metadata:
    name: prod
spec:
---
apiVersion: v1
kind: Namespace
metadata:
    name: manufacturing
spec:
---
apiVersion: v1
kind: Namespace
metadata:
    name: dev
spec:
---
apiVersion: v1
kind: Namespace
metadata:
    name: finance
spec:
---
apiVersion: v1
kind: Namespace
metadata:
    name: finance
spec:
---
apiVersion: v1
kind: Namespace
metadata:
    name: marketing
spec:
---
apiVersion: v1
kind: Namespace
metadata:
    name: research
spec:
---
apiVersion: v1
kind: Pod
metadata:
   name: redis-db
   namespace: marekting
spec:
   containers:
   - name: redis-db
     image: redis
---
apiVersion: v1
kind: Pod
metadata:
   name: blue
   namespace: marketing
spec:
   containers:
   - name: blue
     image: kodekloud/webapp-conntest
---
apiVersion: v1
kind: Pod
metadata:
   name: payroll
   namespace: finance
spec:
   containers:
   - name: payroll
     image: kodekloud/webapp-conntest
---
apiVersion: v1
kind: Pod
metadata:
   name: blue
   namespace: marketing
spec:
   containers:
   - name: blue
     image: kodekloud/webapp-conntest
---
apiVersion: v1
kind: Pod
metadata:
   name: red-app
   namespace: manufacturing
   labels: 
      app: red-app
spec:
   containers:
   - name: red-app
     image: kodekloud/webapp-conntest
---
apiVersion: v1
kind: Pod
metadata:
   name: redis
   namespace: finance
   labels:
spec:
   containers:
   - name: redis
     image: kodekloud/webapp-conntest
---
apiVersion: v1
kind: Pod
metadata:
   name: dna-1
   namespace: research
   labels:
spec:
   containers:
   - name: dna-1
     image: busybox
---
apiVersion: v1
kind: Pod
metadata:
   name: dna-2
   namespace: research
   labels:
spec:
   containers:
   - name: dna-2
     image: busybox
---
