apiVersion: v1
kind: Pod
metadata:
   name: nginx-container
   namespace: default
   labels:
      run: nginx
      name: nginx
spec:
   containers:
   - name: mpuzi
     image: nginx
   - name: mjinga
     image: redis